// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/Tricker-MFV/checkin-internal-system/internal/controller"
	"github.com/Tricker-MFV/checkin-internal-system/internal/controller/http"
	"github.com/Tricker-MFV/checkin-internal-system/internal/controller/http/v1"
	"github.com/Tricker-MFV/checkin-internal-system/internal/database"
	"github.com/Tricker-MFV/checkin-internal-system/internal/repository/implement"
	"github.com/Tricker-MFV/checkin-internal-system/internal/service/implement"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeContainer(db database.Db) *controller.ApiContainer {
	employeeRepository := repositoryimplement.NewEmployeeRepository(db)
	employeeService := serviceimplement.NewEmployeeService(employeeRepository)
	employeeHandler := v1.NewEmployeeHandler(employeeService)
	server := http.NewServer(employeeHandler)
	apiContainer := controller.NewApiContainer(server)
	return apiContainer
}

// wire.go:

var container = wire.NewSet(controller.NewApiContainer)

// may have grpc server in the future
var serverSet = wire.NewSet(http.NewServer)

// handler === controller | with service and repository layers to form 3 layers architecture
var handlerSet = wire.NewSet(v1.NewEmployeeHandler)

var serviceSet = wire.NewSet(serviceimplement.NewEmployeeService)

var repositorySet = wire.NewSet(repositoryimplement.NewEmployeeRepository)
