definitions:
  model.EmployeeResponse:
    properties:
      id:
        type: integer
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/employee:
    get:
      description: Get all employees
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.EmployeeResponse'
            type: array
      summary: Get all employees
      tags:
      - Employee
swagger: "2.0"
